### PR TITLE
fixes #16

### LINKED ISSUE #16: Make it possible to set top_n in most_similar words
Can you please make it possible to choose top_n most similar words instead of having to replace with random synonym from the default 10 synonyms.

### PR DESCRIPTION
**Pull request by AchatY**
now we can  choose top_n most similar words instead of having to replace with random synonym from the default 10 synonyms.

Hope this can help

### CODE REVIEW

**Comment by vukosim** [comment]
@JosephSefara and @CateGitau please look if this adds the functionality. 

@AchatY Thank you so much.

**Comment by vukosim** [comment]
Ohh, why did you delete this @AchatY

**Comment by AchatY** [comment]
Consider the position of the word to be replaced.

Being able to choose the language.

Being able to choose stopwords

Be able to define the top_n of synonymous names on which we can choose

**Comment by vukosim** [comment]
Hey @josephsefara, can you check

**Comment by vukosim** [comment]
Thank you again @AchatY LGTM.

**Pull request merged**
